## Project information
site_name: Raccolta di Regolamenti del Comune di San Giuseppe Jato
site_url: https://regolamenti-rtd.readthedocs.io/en/latest/
site_description: Raccolta di Regolamenti del Comune di San Giuseppe Jato
site_author: Giuseppe Ragusa

## Repository
# repo_url: https://github.com/giuragu/rtd
# repo_name: rtd
# edit_uri: edit/master/docs/

## Configuration
theme:
  name: "material"
  custom_dir: docs/overrides/
  logo: images/San_Giuseppe_Jato.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: it
  features:
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
  icon:
     repo: fontawesome/brands/github
  
  
  
nav:
  - Home: README.md
  - REGOLAMENTO PER L'ISTITUZIONE E LA TENUTA DELL'ALBO COMUNALE DELLE ASSOCIAZIONI E DEL VOLONTARIATO: regolamento-tenuta-albo-associazioni.md
  - Regolamento del Bilancio in Democrazia Partecipata: regolamento-bilancio-democrazia-partecipata.md

 

plugins:
- search
- mkdocstrings


# Extensions
markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- footnotes
- attr_list
- def_list 
- pymdownx.inlinehilite
- meta
- md_in_html
  
  
## extra CSS
extra_css:
   - stylesheets/extra.css


## Custom theme additions
extra_javascript:
   - stylesheets/extra.js

## Social Media
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/giuragu/regolamenti-rtd
    - icon: fontawesome/solid/envelope
      link: mailto:comunesangiuseppejato@pec.it
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/regolamenti-rtd
  
## setting dal progetto originale https://github.com/up42/up42-py/blob/master/mkdocs.yml + https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

## copiright
copyright: <a href="https://www.comune.sangiuseppejato.pa.it/" title="Comune di San Giuseppe Jato " target="_blank">Comune di San Giuseppe Jato </a> | CC BY 4.0 Int Licence
